[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

no_match_coverage = "script|test|mocks|YieldVaultV2|MockAggregatorV3"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
[rpc_endpoints]
arbitrum_sepolia = "${RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[etherscan]
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }